### ISSUE TITLE
RCON For game server control

### ISSUE THREAD

**Issue by Lewimaron** [Cog-Creators/Cog-Board#116]
## Description of cog:

I run a few game servers and I manage a lot of stuff through RCON. Unfortunately this means having a separate rcon client window open for each server which makes a horrible mess on my desktop.
What would be really good is a cog to link the rcon to a discord channel. This would mean any output from the game server would be printed to the channel and any commands sent through the channel would be sent to the server.
To get chat, different games may use different commands to retrieve the chat EG: one of the games I use uses the "getchat" rcon command. This should be a user configurable option and should have an option to auto run every few seconds to pull chat messages.
It would also be really useful so have scheduled commands for regular broadcasts.
In my particular use case I have 5 servers and would like either each server relayed to a different channel, or some kind of identifying message added to each message to indicate which server it came from. It would also be good to have an option to send a command to every connected server for a specific game.

## API's or other information for cog:

Possibly using this?
http://python-valve.readthedocs.io/en/latest/rcon.html

**Comment by Sebass13** [comment]
Any bounty on this?

**Comment by Lewimaron** [comment]
As much as I'd like to, I'm a bit too broke at the moment for anything substantial. How much would you be looking for?

**Comment by Sebass13** [comment]
Hey, I decided to just make this cog for the fun of it, you can see it [here](https://github.com/Sebass13/Sebass-Cogs/tree/master/rcon). Use these commands to install it:
```
[p]cog repo add Sebass-Cogs https://github.com/Sebass13/Sebass-Cogs/
[p]cog install Sebass-Cogs rcon
```

**Comment by Lewimaron** [comment]
Just had a go with it, unfortunately it's giving me a timeout error whenever I try and send a command and it doesn't seem to be outputting any of the chat to the channel. The I'm assuming the rcon port needs to be added as part of the address?

**Comment by Lewimaron** [comment]
Exception in command 'rcon'
Traceback (most recent call last):
  File "/home/jess/Red-DiscordBot/cogs/rcon.py", line 138, in rcon
    res = await self.bot.loop.run_in_executor(None, rcon.execute, command)
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "lib/valve/rcon.py", line 464, in wrapper
    return function(instance, *args, **kwargs)
  File "lib/valve/rcon.py", line 464, in wrapper
    return function(instance, *args, **kwargs)
  File "lib/valve/rcon.py", line 575, in execute
    return self._receive(timeout)
  File "lib/valve/rcon.py", line 435, in _receive
    for _ in self._timer(timeout):
  File "lib/valve/rcon.py", line 387, in _timer
    raise RCONTimeoutError
valve.rcon.RCONTimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/jess/Red-DiscordBot/cogs/rcon.py", line 140, in rcon
    await self.bot.say("Response expected but none received.")
  File "lib/discord/ext/commands/bot.py", line 309, in _augmented_msg
    msg = yield from coro
  File "red.py", line 92, in send_message
    return await super().send_message(*args, **kwargs)
  File "lib/discord/client.py", line 1144, in send_message
    channel_id, guild_id = yield from self._resolve_destination(destination)
  File "lib/discord/client.py", line 289, in _resolve_destination
    raise InvalidArgument(fmt.format(destination))

discord.errors.InvalidArgument: Destination must be Channel, PrivateChannel, User, or Object. Received NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "lib/discord/ext/commands/core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "lib/discord/ext/commands/core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: InvalidArgument: Destination must be Channel, PrivateChannel, User, or Object. Received NoneType
